version: '3'
services:

  hadoop-slave1:
    image: dvillaj/hadoop-cluster-base
    build:
      context: base
    networks:
      - hadoop

  hadoop-slave2:
    image: dvillaj/hadoop-cluster-base
    networks:
      - hadoop

  hadoop-master:
    image: dvillaj/hadoop-cluster-master
    build:
      context: master
    networks:
      - hadoop
    ports:
      - 50070:50070
      - 8088:8088
      - 9000:9000
    depends_on:
      - hadoop-slave1
      - hadoop-slave2   

  mysql:
    image: mysql:5.7
    restart: always
    networks:
      - hadoop
    environment:
      MYSQL_DATABASE: 'metastore'
      MYSQL_USER: 'hive'
      MYSQL_PASSWORD: '3MX6fDLN2AQm23bD'
      MYSQL_ROOT_PASSWORD: 'UvwKXqnrfn27CNVz'
    ports:
      - 3306:3306

  hive:
    image: dvillaj/hive
    build:
      context: hive
    networks:
      - hadoop
    depends_on:
      - mysql
      - hadoop-master
    ports:
      - 10000:10000
      - 10002:10002
      - 9083:9083

    #volumes:
    #   - hive_container:/data          
      
networks:
  hadoop:
    driver: bridge


#volumes:
#  hive_container: