version: '3'
services:

  hadoop-slave1:
    image: dvillaj/hadoop-cluster-base
    build:
      context: base
    networks:
      - global-network
    ports:
      - 8042

  hadoop-slave2:
    image: dvillaj/hadoop-cluster-base
    networks:
      - global-network
    ports:
      - 8042

  hadoop-master:
    image: dvillaj/hadoop-cluster-master
    build:
      context: master
    networks:
      - global-network
    ports:
      - 50070:50070
      - 8088:8088
      - 9000:9000
    depends_on:
      - hadoop-slave1
      - hadoop-slave2   

  mysql:
    image: mysql:5.7
    restart: always
    networks:
      - global-network
    environment:
      MYSQL_DATABASE: 'metastore'
      MYSQL_USER: 'hive'
      MYSQL_PASSWORD: '3MX6fDLN2AQm23bD'
      MYSQL_ROOT_PASSWORD: 'UvwKXqnrfn27CNVz'
    ports:
      - 3306:3306

  hive:
    image: dvillaj/hive
    build:
      context: hive
    networks:
      - global-network
    depends_on:
      - mysql
      - hadoop-master
    ports:
      - 10000:10000
      - 10002:10002
      - 9083:9083

    #volumes:
    #   - hive_container:/data          

  spark-master:
    image: dvillaj/spark-master
    build:
      context: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment: 
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    networks:
      - global-network

  spark-worker:
    build:
      context: spark-worker
    depends_on:
      - spark-master
    env_file:
      - spark-worker.env
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8080
    ports:
      - 8080
    networks:
      - global-network
      
networks:
  global-network:
    driver: bridge


#volumes:
#  hive_container: